### ISSUE TITLE
[enhancement] enable/disable actions feature

### ISSUE THREAD

**Issue by piechart** [AntonPoltoratskyi/NativeUI#1]
Hi
Have been using this lib for a while, enjoy it a lot, thank you for making it.
If only `Alert.Action` could get an ability to be enabled and disabled this would be very much appreciated!
Sometimes if alert has textField(s) it becomes a better UX approach to disable OK or DONE button in case the input value is unacceptable/empty, that's the reason of asking :)

**Comment by devpolant** [comment]
Hi @piechart ! Good idea. I will consider this in the next update, maybe on this weekend or a little bit later.

**Comment by devpolant** [comment]
Done https://github.com/AntonPoltoratskyi/NativeUI/pull/3

**Comment by devpolant** [comment]
Version `1.0.1` released
