### ISSUE TITLE
[potential issue] several alerts displaying problem

### ISSUE THREAD

**Issue by piechart** [AntonPoltoratskyi/NativeUI#2]
When a new alert must be presented as a result of selecting any action button on a previous one, it becomes impossible because action handler executes before AlertViewController is dismissed.
`Warning: Attempt to present <UIAlertController: 0x7fb07a1bba00>  on <...IssueDetailViewController: 0x7fb07a883400> which is already presenting (null)`
If action.handler was executed in AlertViewController.completionHandler that would solve the issue. Not sure if this sequence of action.handler execution will fit all the cases to update current logic with this one

**Comment by devpolant** [comment]
Actually, as far as I remember, the similar issue occurred with native UIAlertController too. 
I think it can be fixed by dismissing alert manually instead of automatic dismiss. I will try to push updates in the near few days. Btw, if you have any proposal feel free to open pull request :)

**Comment by devpolant** [comment]
@piechart Version 1.1.0 released. It contains fix for this issue.

**Comment by devpolant** [comment]
@piechart Please take a look at this paragraph in readme file https://github.com/AntonPoltoratskyi/NativeUI#edge-cases
